config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "top_page#index"
  resources :posts, expect: :index
  resources :users, only: :show
  get '*path', controller: 'application', action: 'render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader

  validates :title, :text, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, length: { maximum: 20 } 

  has_many :posts, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters , if: :devise_controller?


  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path 
    else
      flash.now[:alert] = '『タイトル』と『本文』の入力は必須です。'
      render :new
      
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :image).merge(user_id: current_user.id)
  end

  def logged_in_user
    unless user_signed_in?
      redirect_to root_path
    end
  end
  
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def index
    @posts = Post.all.order(id: "DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: "DESC")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Space blog2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" rel="stylesheet">
    <link rel = "stylesheet" type = "text/css" href = "trix.css">
    <script type = "text/javascript" src = "trix.js" ></script>
  </head>

  <body>
    <div class="wrapper">
      <footer>
        <p>© 2020 Space blog All rights reserved.</p>
      </footer>
      <header>
        <div class="header__title">
          <%=link_to "Space blog", root_path, class: "title"%>
        </div>
          <div class="account">
          <% unless user_signed_in? %>
            <%=link_to "ログイン", new_user_session_path, class: "account__log-in"%>
            <%=link_to "新規登録", new_user_registration_path, class: "account__new"%>
          <% else %>
            <%= link_to current_user.nickname, user_path(current_user), class: "user-name"%> <p>様</p>
            <%=link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "account__new"%>
          <% end %>
          </div>
      </header>
      <% if user_signed_in? %>
        <%=link_to root_path do %>
          <div class="icon1">
            <i class="fas fa-home"></i>
          </div>
        <% end %>
        <% unless request.path.include?("new") %>
          <%=link_to new_post_path do %>
            <div class="icon2">
              <i class="fas fa-plus"></i>
            </div>
          <% end %>
        <% else %>
        <% end %>
      <% else %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="form-box">
  <%= form_with(model: @post, local: true) do |form| %>
    <div class="articles">
      <div class="flash"><%= flash[:alert] %></div>
      <div class="title-box">
        <p>タイトル:</p>
        <%= form.text_field :title, class: "title"%>
      </div>
      <div class="pic">
        <p>サムネイル画像</p>
        <%= form.file_field :image, class: "pic-box"%>
      </div>
      <div class="text-box">
        <p>本文:</p>
        <%= form.hidden_field :text, id: "text"%>
        <trix-editor input="text"></trix-editor>
      </div>
    </div>
    <%= form.submit "更新する", class: "submit"%>
  <% end%>
</div>

app/views/posts/new.html.erb
<div class="form-box">
  <%= form_with(model: @post, local: true) do |form| %>
    <div class="articles">
      <div class="flash"><%= flash[:alert] %></div>
      <div class="title-box">
        <p>タイトル:</p>
        <%= form.text_field :title, class: "title"%>
      </div>
      <div class="pic">
        <p>サムネイル画像</p>
        <%= form.file_field :image, class: "pic-box"%>
      </div>
      <div class="text-box">
        <p>本文:</p>
        <%= form.hidden_field :text, id: "text"%>
        <trix-editor input="text"></trix-editor>
      </div>
    </div>
    <%= form.submit "投稿する", class: "submit"%>
  <% end%>
</div>

app/views/posts/show.html.erb
<div class="posts-box">
  <div class="posted-title">
    <h2>TITLE:</h2><%= @post.title %>
  </div>
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <%= link_to "編集", edit_post_path(@post.id), class: "edit-post" %>
    <%= link_to "削除", post_path(@post.id), class: "delete-post", data: { confirm: "本当に削除しますか？" }, method: :delete %>
  <% end %>
  <div class="posted-pic">
    <% if @post.image?%>
      <%= image_tag @post.image.to_s %>
    <% else %>
      <%= image_tag "no_image.png"%>
    <% end %>
  </div>
  <div class="posted-text">
    <%= @post.text.html_safe %>
  </div>
</div>

app/views/top_page/index.html.erb
<div class="contents">
  <% @posts.each do |post| %>
    <%=link_to post_path(post) do%>
    <div class="posts">
      <% if post.image? %>
        <%= image_tag post.image.to_s %>
      <% end %>
      <div class="author"><%= post.user.nickname%></div>
      <div class="title">
        <p><%= post.title %></p>
      </div>
    </div>
    <% end %>
  <% end %>
<div>

app/views/users/show.html.erb
<div class="page-title">
  <p>マイページ</p>
  <%=link_to edit_user_registration_path do %>
    <i class="fas fa-id-card"><p>登録情報</p></i>
  <% end%>
</div>
<div class="contents-box">
  <% @posts.each do |post| %>
    <%=link_to post_path(post) do%>
      <div class="posts">
        <% if post.image? %>
          <%= image_tag post.image.to_s %>
        <% end %>
        <div class="title">
          <p><%= post.title %></p>
        </div>
      </div>
    <% end %>
  <% end %>
<div>